# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'PhotoFilter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Swinject'
  pod 'SwinjectStoryboard'
  pod 'IGListKit'

  # Pods for PhotoFilter

  target 'PhotoFilterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
